# Generated by Django 3.0.1 on 2020-03-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRiskAspects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RiskAspect_Name', models.CharField(max_length=200, verbose_name='Risk Aspect Name')),
                ('RiskAspect_Description', models.TextField(verbose_name='Risk Aspect Description')),
                ('CreatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
